"""
Physical-plausibility validation for a cached XFOIL polar set.

The polar cache is generated by an external solver that fails quietly: when XFOIL
cannot converge an alpha it simply omits the row, and when it converges onto the
wrong (separated) branch it writes a number that is perfectly well-formed and
completely wrong. Neither shows up as an error, so the cache needs checking
against physics rather than against exceptions. This script is that check.

Five checks, run per airfoil cache directory:

1. Alpha coverage -- every Reynolds curve spans the same alpha range on the same
   step, with no interior gaps left by non-converged alphas.
2. Lift-curve slope -- dCl/dalpha through the attached-flow region stays near the
   thin-airfoil value of 2*pi per radian (~0.11 /deg). A branch jump shows up
   here as a slope several times theory, usually negative.
3. Pre-stall monotonicity -- Cl rises with alpha below the stall shoulder. Small
   dips near a laminar separation bubble are tolerated; a collapse is not.
4. Drag sanity -- Cd strictly positive everywhere, and minimum Cd falling as
   Reynolds number rises.
5. Reynolds-trend monotonicity -- Cl(0), Cl_max, Cd_min and max L/D all vary
   monotonically with Re. This is the check that catches a cache where individual
   curves each look plausible but the family is internally inconsistent, which is
   exactly the failure mode the Ncrit=9 S809 cache had.

Run directly: `python -m validation.validate_polars [airfoil]` (from src/),
default airfoil s809.

Author: MJ Hendrikse
Project: DSP810S -- Inverse Design of Small Wind Turbine Blades
"""

import argparse
import glob
import os
import re as re_module
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.abspath(os.path.join(_HERE, "..", "..", "data"))

_FNAME_RE = re_module.compile(r"_Re(\d+)\.csv$", re_module.IGNORECASE)

# Thin-airfoil theory gives dCl/dalpha = 2*pi per radian; viscous effects pull the
# real slope slightly below it. Anything far above is a solver artefact, not lift.
_THEORY_SLOPE_PER_DEG = 2.0 * np.pi * np.pi / 180.0  # ~0.1097
_SLOPE_TOLERANCE = 2.0   # allow up to 2x theory before flagging
_MAX_PRESTALL_DROP = 0.10  # largest tolerated Cl decrease below the stall shoulder


def load_cache(cache_dir):
    """Load every <LABEL>_Re<value>.csv in cache_dir, sorted by Reynolds number."""
    paths = sorted(glob.glob(os.path.join(cache_dir, "*_Re*.csv")))
    if not paths:
        raise FileNotFoundError(f"No cached polar CSVs found in '{cache_dir}'.")

    curves = {}
    for path in paths:
        match = _FNAME_RE.search(os.path.basename(path))
        if not match:
            continue
        data = np.loadtxt(path, delimiter=",", skiprows=1)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        curves[int(match.group(1))] = data
    return dict(sorted(curves.items()))


def check_1_alpha_coverage(curves):
    """
    Every Reynolds curve must span the same alpha range with no unusable holes.

    A single dropped alpha is not automatically a defect: PolarLookup fills it by
    linear interpolation between converged neighbours one step either side, and
    over one step of an attached-flow polar that is an accurate reconstruction.
    Two or more *consecutive* dropped alphas is a different matter — the span
    being interpolated is then wide enough to cut a corner off the curve, and
    XFOIL failing repeatedly in one place usually means the solution is genuinely
    ill-behaved there rather than merely unlucky.

    So an isolated dropout passes only if it earns it: linear interpolation across
    the hole is compared against a local quadratic fit through the surrounding
    converged points, and the two must agree closely. That way the check is
    measuring whether the gap is actually harmless, not assuming it.
    """
    print("=== Check 1: alpha coverage ===")
    ok = True

    for re, d in curves.items():
        alpha, cl = d[:, 0], d[:, 1]
        step = float(np.min(np.diff(alpha)))
        expected = np.round(np.arange(alpha[0], alpha[-1] + step / 2, step), 6)
        missing = np.setdiff1d(expected, np.round(alpha, 6))

        # Group consecutive dropouts.
        runs = []
        for a in missing:
            if runs and abs(a - runs[-1][-1] - step) < 1e-6:
                runs[-1].append(a)
            else:
                runs.append([a])

        if not runs:
            print(f"  Re={re:>7,}: {len(alpha):3d} pts, alpha {alpha[0]:+.1f} to "
                  f"{alpha[-1]:+.1f}, step {step:.2f} -- complete")
            continue

        wide = [r for r in runs if len(r) > 1]
        if wide:
            ok = False
            print(f"  Re={re:>7,}: [FAIL] consecutive dropouts "
                  f"{[[float(a) for a in r] for r in wide]}")

        for run in (r for r in runs if len(r) == 1):
            a_gap = float(run[0])
            lin = float(np.interp(a_gap, alpha, cl))
            # Local quadratic through the two converged points either side.
            near = np.argsort(np.abs(alpha - a_gap))[:4]
            quad = float(np.polyval(np.polyfit(alpha[near], cl[near], 2), a_gap))
            err = abs(lin - quad)
            verdict = "harmless" if err < 0.01 else "SUSPECT"
            if err >= 0.01:
                ok = False
            print(f"  Re={re:>7,}: {len(alpha):3d} pts -- isolated dropout at alpha "
                  f"{a_gap:+.1f}; interp Cl={lin:.4f} vs local quadratic {quad:.4f} "
                  f"(diff {err:.4f}) -- {verdict}")

    spans = {(float(d[0, 0]), float(d[-1, 0])) for d in curves.values()}
    if len(spans) != 1:
        print(f"  [FAIL] Reynolds curves do not share one alpha span: {sorted(spans)}")
        ok = False
    else:
        print(f"  All curves share alpha span {spans.pop()}")
    print("  ->", "PASS" if ok else "FAIL")
    return ok


def check_2_lift_slope(curves):
    print("=== Check 2: lift-curve slope vs thin-airfoil theory ===")
    ok = True
    limit = _THEORY_SLOPE_PER_DEG * _SLOPE_TOLERANCE
    for re, d in curves.items():
        alpha, cl = d[:, 0], d[:, 1]
        # Attached-flow window: below the stall shoulder, above negative stall.
        window = (alpha >= -4.0) & (alpha <= 6.0)
        fit = np.polyfit(alpha[window], cl[window], 1)[0]
        slope = np.diff(cl) / np.diff(alpha)
        worst = float(np.max(np.abs(slope)))
        a_worst = float(alpha[int(np.argmax(np.abs(slope)))])
        flag = "ok" if worst <= limit else f"EXCEEDS {limit:.3f} at alpha={a_worst:+.1f}"
        if worst > limit:
            ok = False
        print(f"  Re={re:>7,}: linear-fit slope {fit:.4f} /deg "
              f"(theory {_THEORY_SLOPE_PER_DEG:.4f}), max |dCl/dalpha| {worst:.3f} -- {flag}")
    print("  ->", "PASS" if ok else "FAIL")
    return ok


def check_3_prestall_monotonicity(curves):
    print("=== Check 3: pre-stall Cl monotonicity ===")
    ok = True
    for re, d in curves.items():
        alpha, cl = d[:, 0], d[:, 1]
        a_stall = float(alpha[int(np.argmax(cl))])
        # Only inspect below the stall shoulder; past Cl_max a falling Cl is the
        # physically correct behaviour, not a defect.
        drops = []
        for i in range(len(alpha) - 1):
            if alpha[i] >= a_stall - 2.0:
                continue
            delta = cl[i + 1] - cl[i]
            if delta < 0:
                drops.append((float(alpha[i]), float(alpha[i + 1]), float(delta)))
        worst = min((d_[2] for d_ in drops), default=0.0)
        if worst < -_MAX_PRESTALL_DROP:
            ok = False
            detail = " | ".join(f"alpha {a:+.1f}->{b:+.1f} dCl={c:+.3f}"
                                for a, b, c in drops if c < -_MAX_PRESTALL_DROP)
            print(f"  Re={re:>7,}: [FAIL] {detail}")
        else:
            print(f"  Re={re:>7,}: {len(drops)} minor dip(s), worst dCl={worst:+.4f} "
                  f"(tolerance {-_MAX_PRESTALL_DROP:+.2f}) -- ok")
    print("  ->", "PASS" if ok else "FAIL")
    return ok


def check_4_drag_sanity(curves):
    print("=== Check 4: drag sanity ===")
    ok = True
    cd_mins = []
    for re, d in curves.items():
        cd = d[:, 2]
        if np.any(cd <= 0):
            print(f"  Re={re:>7,}: [FAIL] non-positive Cd present")
            ok = False
            continue
        cd_mins.append(float(cd.min()))
        print(f"  Re={re:>7,}: Cd in [{cd.min():.5f}, {cd.max():.5f}] -- positive")

    if len(cd_mins) == len(curves) and any(
            cd_mins[i + 1] > cd_mins[i] for i in range(len(cd_mins) - 1)):
        print("  [FAIL] minimum Cd does not fall monotonically with Reynolds number")
        ok = False
    else:
        print("  Minimum Cd falls monotonically with Reynolds number")
    print("  ->", "PASS" if ok else "FAIL")
    return ok


def check_5_reynolds_trends(curves):
    print("=== Check 5: monotonic Reynolds trends ===")
    res = list(curves)
    cl0, clmax, ldmax = [], [], []
    for re, d in curves.items():
        alpha, cl, cd = d[:, 0], d[:, 1], d[:, 2]
        cl0.append(float(np.interp(0.0, alpha, cl)))
        clmax.append(float(cl.max()))
        ldmax.append(float((cl / cd).max()))
        print(f"  Re={re:>7,}: Cl(0)={cl0[-1]:+.3f}  Cl_max={clmax[-1]:.3f}  "
              f"max L/D={ldmax[-1]:5.1f}")

    ok = True
    for name, series, want_increasing in (("Cl_max", clmax, True),
                                          ("max L/D", ldmax, True)):
        increasing = all(series[i + 1] >= series[i] for i in range(len(series) - 1))
        if increasing != want_increasing:
            print(f"  [FAIL] {name} is not monotonically "
                  f"{'increasing' if want_increasing else 'decreasing'} with Re: {series}")
            ok = False
        else:
            print(f"  {name} increases monotonically with Re")

    # Cl(0) is set by camber, so it should be near-constant across Re rather than
    # trending. A cache that jumps here is on inconsistent solution branches.
    spread = max(cl0) - min(cl0)
    if spread > 0.05:
        print(f"  [FAIL] Cl(0) varies by {spread:.3f} across Re "
              f"(expected near-constant, camber-set)")
        ok = False
    else:
        print(f"  Cl(0) near-constant across Re (spread {spread:.3f})")
    print("  ->", "PASS" if ok else "FAIL")
    return ok


def validate(airfoil):
    cache_dir = os.path.join(DATA_DIR, "polars", airfoil)
    print("=" * 68)
    print(f"Validating polar cache: {airfoil}  ({cache_dir})")
    print("=" * 68)
    curves = load_cache(cache_dir)

    results = [
        check_1_alpha_coverage(curves),
        check_2_lift_slope(curves),
        check_3_prestall_monotonicity(curves),
        check_4_drag_sanity(curves),
        check_5_reynolds_trends(curves),
    ]

    print("=" * 68)
    passed = sum(results)
    print(f"{passed}/{len(results)} checks passed"
          f"{'' if passed == len(results) else ' -- CACHE NOT TRUSTWORTHY'}")
    return all(results)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Validate a cached polar set.")
    parser.add_argument("airfoil", nargs="?", default="s809",
                        help="Cache subfolder under data/polars/ (default: s809).")
    args = parser.parse_args()
    sys.exit(0 if validate(args.airfoil) else 1)
